[default.extend-words]
ix = "ix"
iy = "iy"
iz = "iz"
nd = "nd"
pn = "pn"
hel = "hel"
Stoer = "Stoer"
nax = "nax"
yoh = "yoh"
offsetp = "offsetp"
Fo = "Fo"
WHT = "WHT"
ba = "ba"
wheight = "wheight"
precesses = "precesses"
[files]
extend-exclude = [
"src/glad.*",
"src/derivatives.c",
"docs/javascripts",
"live.html",
]
