name: REBOUNDx (python)

on: [push, pull_request]

jobs:
  build:
    name: Python tests on ${{ matrix.os }} (${{ matrix.python-version }})
    timeout-minutes: 10

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          path: rebound
      - uses: actions/checkout@v4
        with:
          repository: dtamayo/reboundx
          path: reboundx
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest wheel setuptools
          pip install -r rebound/requirements.txt
          pip install -r reboundx/requirements.txt
      - name: Build REBOUND package
        run: pip install ./rebound
      - name: Build REBOUNDx package
        run: pip install --no-build-isolation -e ./reboundx -v
      - name: Run REBOUNDx unit tests
        run: |
          cd reboundx
          python -m unittest discover -s reboundx/test/ -v
